const router = require("express").Router();
const prisma = require("../db");
const { authenticate, allow } = require("../middleware");

async function cartFor(userId) { return prisma.cart.upsert({ where: { userId }, update: {}, create: { userId }, include: { items: { include: { product: true } } } }); }
router.use(authenticate, allow("STUDENT"));
router.get("/", async (req, res, next) => { try { res.json(await cartFor(Number(req.auth.sub))); } catch (e) { next(e); } });
router.post("/items", async (req, res, next) => { try { const userId = Number(req.auth.sub), productId = Number(req.body.productId), quantity = Number(req.body.quantity || 1); if (!Number.isInteger(quantity) || quantity < 1) return res.status(400).json({ error: "Quantity must be a positive integer" }); const product = await prisma.product.findUnique({ where: { id: productId } }); if (!product || !product.isActive || product.stock < quantity) return res.status(400).json({ error: "Product unavailable or insufficient stock" }); const cart = await prisma.cart.upsert({ where: { userId }, update: {}, create: { userId } }); await prisma.cartItem.upsert({ where: { cartId_productId: { cartId: cart.id, productId } }, update: { quantity }, create: { cartId: cart.id, productId, quantity } }); res.status(201).json(await cartFor(userId)); } catch (e) { next(e); } });
router.patch("/items/:productId", async (req, res, next) => { try { const userId = Number(req.auth.sub), quantity = Number(req.body.quantity); if (!Number.isInteger(quantity) || quantity < 1) return res.status(400).json({ error: "Quantity must be a positive integer" }); const cart = await prisma.cart.findUnique({ where: { userId } }); if (!cart) return res.status(404).json({ error: "Cart not found" }); const product = await prisma.product.findUnique({ where: { id: Number(req.params.productId) } }); if (!product || product.stock < quantity) return res.status(400).json({ error: "Insufficient stock" }); await prisma.cartItem.update({ where: { cartId_productId: { cartId: cart.id, productId: product.id } }, data: { quantity } }); res.json(await cartFor(userId)); } catch (e) { next(e); } });
router.delete("/items/:productId", async (req, res, next) => { try { const cart = await prisma.cart.findUnique({ where: { userId: Number(req.auth.sub) } }); if (cart) await prisma.cartItem.deleteMany({ where: { cartId: cart.id, productId: Number(req.params.productId) } }); res.status(204).end(); } catch (e) { next(e); } });
module.exports = router;
